#/bin/bash

PYTHON_VERSION='3.6.1';
PYTHON_SOURCE_DIR="Python-$PYTHON_VERSION";
PYTHON_SOURCE_URL="https://www.python.org/ftp/python";

DOCKER_FILE_NAME='Dockerfile';
DOCKER_WORKING_DIR='/pop';
DOCKER_IMAGE_NAME='amazonlinux';
DOCKER_PYTHON_IMAGE_NAME="$DOCKER_IMAGE_NAME-python3:$PYTHON_VERSION";
DOCKER_PYTHON_CONTAINER_NAME="$DOCKER_IMAGE_NAME-python3-container";

PROJECT_BUILD_DIR='build'
PROJECT_LOCAL_DIR="$PROJECT_BUILD_DIR/local";
PROJECT_REMOTE_DIR="$PROJECT_BUILD_DIR/remote";
PROJECT_ARCHIVE='lambda.zip';
PROJECT_SOURCES='src';
PROJECT_ENTRY_POINT='lambda_function.py'
