#/bin/bash

PYTHON_VERSION_MAIN='3';
PYTHON_VERSION_SUB='6';
PYTHON_VERSION_REV='1';
PYTHON_VERSION="$PYTHON_VERSION_MAIN.$PYTHON_VERSION_SUB.$PYTHON_VERSION_REV";
PYTHON_SOURCE_DIR="Python-$PYTHON_VERSION";
PYTHON_SOURCE_URL="https://www.python.org/ftp/python";
PYTHON_STATIC_LIBRARY=libpython$PYTHON_VERSION_MAIN.${PYTHON_VERSION_SUB}m.a

POP_PYTHON_DIR='pop-python3';
POP_PYTHON_SRC="$POP_PYTHON_DIR/main.c";
POP_PYTHON_OUT='pop_python3';

DOCKER_FILE_NAME='Dockerfile';
DOCKER_WORKING_DIR='/pop';
DOCKER_IMAGE_NAME='amazonlinux';
DOCKER_PYTHON_IMAGE_NAME="$DOCKER_IMAGE_NAME-python3:$PYTHON_VERSION";
DOCKER_PYTHON_CONTAINER_NAME="$DOCKER_IMAGE_NAME-python3-container";

PROJECT_BUILD_DIR='build'
PROJECT_LOCAL_DIR="$PROJECT_BUILD_DIR/local";
PROJECT_REMOTE_DIR="$PROJECT_BUILD_DIR/remote";
PROJECT_ARCHIVE='lambda.zip';
PROJECT_SOURCES='src';
PROJECT_ENTRY_POINT='lambda_function.py'
